/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Button".
 */
export type Button =
  | {
      title?: string | null;
      linkType?: ("External" | "Internal") | null;
      link?: string | null;
      internalLink?: {
        relationTo: "posts";
        value: string | Post;
      } | null;
      /**
       * Should this open in a new browser window/tab?
       */
      openInNewTab?: boolean | null;
      isPrimary?: boolean | null;
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    user_sessions: UserSession;
    user_accounts: UserAccount;
    user_verifications: UserVerification;
    oauth_application: OauthApplication;
    oauth_access_token: OauthAccessToken;
    oauth_consent: OauthConsent;
    jwks: Jwk;
    user_subscriptions: UserSubscription;
    media: Media;
    categories: Category;
    posts: Post;
    pages: Page;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      relatedDocs: "posts";
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    user_sessions: UserSessionsSelect<false> | UserSessionsSelect<true>;
    user_accounts: UserAccountsSelect<false> | UserAccountsSelect<true>;
    user_verifications: UserVerificationsSelect<false> | UserVerificationsSelect<true>;
    oauth_application: OauthApplicationSelect<false> | OauthApplicationSelect<true>;
    oauth_access_token: OauthAccessTokenSelect<false> | OauthAccessTokenSelect<true>;
    oauth_consent: OauthConsentSelect<false> | OauthConsentSelect<true>;
    jwks: JwksSelect<false> | JwksSelect<true>;
    user_subscriptions: UserSubscriptionsSelect<false> | UserSubscriptionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences": PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    "payload-migrations": PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    logo: Logo;
    plans: Plan;
    homepage: Homepage;
    "blog-page": BlogPage;
    navbar: Navbar;
    footer: Footer;
  };
  globalsSelect: {
    logo: LogoSelect<false> | LogoSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    "blog-page": BlogPageSelect<false> | BlogPageSelect<true>;
    navbar: NavbarSelect<false> | NavbarSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: "lt" | "en";
  user: User & {
    collection: "users";
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  email: string;
  role: "user" | "admin";
  /**
   * Whether the user is banned
   */
  banned?: boolean | null;
  /**
   * Reason for the ban
   */
  banReason?: string | null;
  /**
   * When the ban expires (leave empty for permanent ban)
   */
  banExpires?: string | null;
  emailVerified: boolean;
  image?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user_sessions".
 */
export interface UserSession {
  id: string;
  userId: string | User;
  token: string;
  expiresAt: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  /**
   * ID of the admin user who is impersonating this session
   */
  impersonatedBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user_accounts".
 */
export interface UserAccount {
  id: string;
  userId: string | User;
  accountId: string;
  providerId: string;
  accessToken?: string | null;
  refreshToken?: string | null;
  accessTokenExpiresAt?: string | null;
  refreshTokenExpiresAt?: string | null;
  scope?: string | null;
  idToken?: string | null;
  password?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user_verifications".
 */
export interface UserVerification {
  id: string;
  identifier: string;
  value: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oauth_application".
 */
export interface OauthApplication {
  id: string;
  /**
   * Unique identifier for each OAuth client
   */
  clientId: string;
  /**
   * Secret key for the OAuth client. Optional for public clients using PKCE.
   */
  clientSecret?: string | null;
  /**
   * Name of the OAuth client
   */
  name: string;
  /**
   * Comma-separated list of redirect URLs
   */
  redirectURLs?: string | null;
  /**
   * Additional metadata for the OAuth client (JSON string)
   */
  metadata?: string | null;
  /**
   * Type of OAuth client
   */
  type: "web" | "mobile" | "public";
  /**
   * Indicates if the client is disabled
   */
  disabled?: boolean | null;
  /**
   * ID of the user who owns the client (optional)
   */
  userId?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oauth_access_token".
 */
export interface OauthAccessToken {
  id: string;
  /**
   * Access token issued to the client
   */
  accessToken: string;
  /**
   * Refresh token issued to the client
   */
  refreshToken?: string | null;
  /**
   * Expiration date of the access token
   */
  accessTokenExpiresAt: string;
  /**
   * Expiration date of the refresh token
   */
  refreshTokenExpiresAt?: string | null;
  clientId: string | OauthApplication;
  /**
   * ID of the user associated with the token
   */
  userId: string | User;
  /**
   * Comma-separated list of scopes granted
   */
  scopes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oauth_consent".
 */
export interface OauthConsent {
  id: string;
  /**
   * ID of the user who gave consent
   */
  userId: string | User;
  /**
   * ID of the OAuth client
   */
  clientId: string | OauthApplication;
  /**
   * Comma-separated list of scopes consented to
   */
  scopes?: string | null;
  /**
   * Indicates if consent was given
   */
  consentGiven: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jwks".
 */
export interface Jwk {
  id: string;
  /**
   * The public part of the web key
   */
  publicKey: string;
  /**
   * The private part of the web key
   */
  privateKey: string;
  /**
   * Timestamp of when the web key expires
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user_subscriptions".
 */
export interface UserSubscription {
  /**
   * Polar.sh subscription ID
   */
  id: string;
  /**
   * The user this subscription belongs to
   */
  userId?: (string | null) | User;
  /**
   * Subscription amount in cents (e.g., 2900 for $29.00)
   */
  amount: number;
  currency: "usd" | "eur";
  /**
   * Billing interval for this subscription
   */
  recurringInterval: "month" | "year";
  status:
    | "active"
    | "canceled"
    | "past_due"
    | "unpaid"
    | "trialing"
    | "incomplete"
    | "incomplete_expired";
  /**
   * Start date of the current billing period
   */
  currentPeriodStart: string;
  /**
   * End date of the current billing period
   */
  currentPeriodEnd: string;
  /**
   * Whether the subscription will be canceled at the end of the current period
   */
  cancelAtPeriodEnd?: boolean | null;
  /**
   * Date when the subscription was canceled
   */
  canceledAt?: string | null;
  /**
   * Date when the subscription started
   */
  startedAt: string;
  /**
   * Date when the subscription will end
   */
  endsAt?: string | null;
  /**
   * Date when the subscription ended
   */
  endedAt?: string | null;
  /**
   * Polar.sh customer ID
   */
  customerId: string;
  /**
   * Polar.sh product ID
   */
  productId: string;
  /**
   * Polar.sh discount ID if applicable
   */
  discountId?: string | null;
  /**
   * Polar.sh checkout ID
   */
  checkoutId: string;
  /**
   * Reason provided by customer for cancellation
   */
  customerCancellationReason?: string | null;
  /**
   * Additional comments from customer about cancellation
   */
  customerCancellationComment?: string | null;
  /**
   * Date when the subscription was last modified
   */
  modifiedAt?: string | null;
  /**
   * Additional metadata as JSON string
   */
  metadata?: string | null;
  /**
   * Custom field data as JSON string
   */
  customFieldData?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  title?: string | null;
  altDescription?: string | null;
  credit?: {
    /**
     * Leave a name for who or what created or captured this image.
     */
    creator?: string | null;
    /**
     * Choose if the creator is an organization or a person.
     */
    creatorType?: ("Person" | "Organization") | null;
    /**
     * Link to the creator's website
     */
    creatorLink?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug?: string | null;
  content?: {
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ("ltr" | "rtl") | null;
        format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  relatedDocs?: {
    docs?: (string | Post)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    /**
     * Include an alternative URL. Overwrites the default URL.
     */
    canonical?: string | null;
    siteName?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  slug?: string | null;
  status?: ("draft" | "published") | null;
  featured?: boolean | null;
  date?: string | null;
  link?: string | null;
  content?: {
    description?: string | null;
    summary?: string | null;
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ("ltr" | "rtl") | null;
        format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    authors?: (string | User)[] | null;
    category?: (string | Category)[] | null;
    media?: {
      includeAudio?: boolean | null;
      includeVideo?: boolean | null;
      /**
       * Include a direct link to podcast audio.
       */
      audio?: string | null;
      videoHost?: ("youtube" | "vimeo") | null;
      /**
       * Use the "youtu.be" share link
       */
      youtube?: string | null;
      /**
       * Only include the numbers after the "vimeo" portion of the link
       */
      vimeo?: string | null;
    };
    image?: {
      /**
       * Recommended size is 640x360 (16:9 aspect ratio)
       */
      image?: (string | null) | Media;
      /**
       * Choose how you want to align the background image in the hero section. This does not change the placement of the image in the flow of the page.
       */
      imagePosition?:
        | (
            | "backgroundTop"
            | "backgroundBottom"
            | "backgroundCenter"
            | "backgroundLeft"
            | "backgroundRight"
          )
        | null;
    };
    richText_html?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    /**
     * Include an alternative URL. Overwrites the default URL.
     */
    canonical?: string | null;
    siteName?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug?: string | null;
  status?: ("draft" | "published") | null;
  showNavbar?: boolean | null;
  showFooter?: boolean | null;
  layout?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ("ltr" | "rtl") | null;
                format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            backgroundImage?: (string | null) | Media;
            ctaText?: string | null;
            ctaLink?: string | null;
            secondaryCtaText?: string | null;
            secondaryCtaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: "hero";
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ("ltr" | "rtl") | null;
                format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            content_html?: string | null;
            alignment?: ("left" | "center" | "right") | null;
            id?: string | null;
            blockName?: string | null;
            blockType: "text";
          }
        | {
            image: string | Media;
            caption?: string | null;
            alignment?: ("left" | "center" | "right" | "full") | null;
            id?: string | null;
            blockName?: string | null;
            blockType: "image";
          }
        | {
            title: string;
            description?: string | null;
            buttonText: string;
            buttonLink: string;
            secondaryButtonText?: string | null;
            secondaryButtonLink?: string | null;
            backgroundColor?: ("default" | "primary" | "secondary") | null;
            id?: string | null;
            blockName?: string | null;
            blockType: "cta";
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            features: {
              title: string;
              description?: string | null;
              icon?: (string | null) | Media;
              id?: string | null;
            }[];
            columns?: ("2" | "3" | "4") | null;
            id?: string | null;
            blockName?: string | null;
            blockType: "features";
          }
        | ContentWithMediaProps
        | {
            title?: string | null;
            subtitle?: string | null;
            testimonials: {
              quote: string;
              authorName: string;
              authorTitle?: string | null;
              authorImage?: (string | null) | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: "testimonials";
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            stats: {
              /**
               * The metric value (e.g., '3M+', '99%', '500+')
               */
              value: string;
              /**
               * Description of the metric
               */
              label: string;
              id?: string | null;
            }[];
            backgroundColor?: ("default" | "primary" | "secondary") | null;
            id?: string | null;
            blockName?: string | null;
            blockType: "stats";
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: "faq";
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    /**
     * Include an alternative URL. Overwrites the default URL.
     */
    canonical?: string | null;
    siteName?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentWithMediaProps".
 */
export interface ContentWithMediaProps {
  active?: boolean | null;
  headerSection?: HeaderSectionProps;
  image?: {
    /**
     * Recommended size is 640x360 (16:9 aspect ratio)
     */
    image?: (string | null) | Media;
    /**
     * Choose how you want to align the background image in the hero section. This does not change the placement of the image in the flow of the page.
     */
    imagePosition?:
      | (
          | "backgroundTop"
          | "backgroundBottom"
          | "backgroundCenter"
          | "backgroundLeft"
          | "backgroundRight"
        )
      | null;
  };
  imageOrientation?: ("landscape" | "square") | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  buttons?: Button;
  /**
   * Which side of the screen should the text show up on on bigger screens? Or do you want the image to be in the background
   */
  textPosition?: ("Left" | "Right" | "Foreground") | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "cwm";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderSectionProps".
 */
export interface HeaderSectionProps {
  headerText?: string | null;
  headerLevel?: ("h2" | "h3" | "h4" | "h5" | "h6") | null;
  anchor?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: "users";
        value: string | User;
      } | null)
    | ({
        relationTo: "user_sessions";
        value: string | UserSession;
      } | null)
    | ({
        relationTo: "user_accounts";
        value: string | UserAccount;
      } | null)
    | ({
        relationTo: "user_verifications";
        value: string | UserVerification;
      } | null)
    | ({
        relationTo: "oauth_application";
        value: string | OauthApplication;
      } | null)
    | ({
        relationTo: "oauth_access_token";
        value: string | OauthAccessToken;
      } | null)
    | ({
        relationTo: "oauth_consent";
        value: string | OauthConsent;
      } | null)
    | ({
        relationTo: "jwks";
        value: string | Jwk;
      } | null)
    | ({
        relationTo: "user_subscriptions";
        value: string | UserSubscription;
      } | null)
    | ({
        relationTo: "media";
        value: string | Media;
      } | null)
    | ({
        relationTo: "categories";
        value: string | Category;
      } | null)
    | ({
        relationTo: "posts";
        value: string | Post;
      } | null)
    | ({
        relationTo: "pages";
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  role?: T;
  banned?: T;
  banReason?: T;
  banExpires?: T;
  emailVerified?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user_sessions_select".
 */
export interface UserSessionsSelect<T extends boolean = true> {
  userId?: T;
  token?: T;
  expiresAt?: T;
  ipAddress?: T;
  userAgent?: T;
  impersonatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user_accounts_select".
 */
export interface UserAccountsSelect<T extends boolean = true> {
  userId?: T;
  accountId?: T;
  providerId?: T;
  accessToken?: T;
  refreshToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  idToken?: T;
  password?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user_verifications_select".
 */
export interface UserVerificationsSelect<T extends boolean = true> {
  identifier?: T;
  value?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oauth_application_select".
 */
export interface OauthApplicationSelect<T extends boolean = true> {
  clientId?: T;
  clientSecret?: T;
  name?: T;
  redirectURLs?: T;
  metadata?: T;
  type?: T;
  disabled?: T;
  userId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oauth_access_token_select".
 */
export interface OauthAccessTokenSelect<T extends boolean = true> {
  accessToken?: T;
  refreshToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  clientId?: T;
  userId?: T;
  scopes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oauth_consent_select".
 */
export interface OauthConsentSelect<T extends boolean = true> {
  userId?: T;
  clientId?: T;
  scopes?: T;
  consentGiven?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jwks_select".
 */
export interface JwksSelect<T extends boolean = true> {
  publicKey?: T;
  privateKey?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user_subscriptions_select".
 */
export interface UserSubscriptionsSelect<T extends boolean = true> {
  id?: T;
  userId?: T;
  amount?: T;
  currency?: T;
  recurringInterval?: T;
  status?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  cancelAtPeriodEnd?: T;
  canceledAt?: T;
  startedAt?: T;
  endsAt?: T;
  endedAt?: T;
  customerId?: T;
  productId?: T;
  discountId?: T;
  checkoutId?: T;
  customerCancellationReason?: T;
  customerCancellationComment?: T;
  modifiedAt?: T;
  metadata?: T;
  customFieldData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  altDescription?: T;
  credit?:
    | T
    | {
        creator?: T;
        creatorType?: T;
        creatorLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?:
    | T
    | {
        description?: T;
      };
  relatedDocs?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        siteName?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  featured?: T;
  date?: T;
  link?: T;
  content?:
    | T
    | {
        description?: T;
        summary?: T;
        richText?: T;
        authors?: T;
        category?: T;
        media?:
          | T
          | {
              includeAudio?: T;
              includeVideo?: T;
              audio?: T;
              videoHost?: T;
              youtube?: T;
              vimeo?: T;
            };
        image?:
          | T
          | {
              image?: T;
              imagePosition?: T;
            };
        richText_html?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        siteName?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  showNavbar?: T;
  showFooter?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              backgroundImage?: T;
              ctaText?: T;
              ctaLink?: T;
              secondaryCtaText?: T;
              secondaryCtaLink?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              content?: T;
              content_html?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              secondaryButtonText?: T;
              secondaryButtonLink?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              title?: T;
              subtitle?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        cwm?: T | ContentWithMediaPropsSelect<T>;
        testimonials?:
          | T
          | {
              title?: T;
              subtitle?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorTitle?: T;
                    authorImage?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              title?: T;
              subtitle?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        siteName?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentWithMediaProps_select".
 */
export interface ContentWithMediaPropsSelect<T extends boolean = true> {
  active?: T;
  headerSection?: T | HeaderSectionPropsSelect<T>;
  image?:
    | T
    | {
        image?: T;
        imagePosition?: T;
      };
  imageOrientation?: T;
  content?: T;
  buttons?: T | ButtonSelect<T>;
  textPosition?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderSectionProps_select".
 */
export interface HeaderSectionPropsSelect<T extends boolean = true> {
  headerText?: T;
  headerLevel?: T;
  anchor?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Button_select".
 */
export interface ButtonSelect<T extends boolean = true> {
  title?: T;
  linkType?: T;
  link?: T;
  internalLink?: T;
  openInNewTab?: T;
  isPrimary?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logo".
 */
export interface Logo {
  id: string;
  light?: (string | null) | Media;
  dark?: (string | null) | Media;
  alt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage pricing plans displayed on the landing page and paywall
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: string;
  plans?:
    | {
        /**
         * Internal identifier (e.g., 'quick-scan', 'team-fit')
         */
        key: string;
        /**
         * Plan name (e.g., '7D Quick Scan')
         */
        name: string;
        /**
         * Plan description
         */
        description: string;
        /**
         * Price in euros (e.g., 29 for €29)
         */
        price: number;
        /**
         * Call-to-action button text
         */
        cta: string;
        /**
         * List of features included in this plan
         */
        features: {
          feature: string;
          id?: string | null;
        }[];
        /**
         * Polar.sh product ID (UUID) for checkout integration and subscription matching
         */
        productKey: string;
        /**
         * Whether this plan is currently available
         */
        isActive?: boolean | null;
        /**
         * Display order (lower numbers first)
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit the landing page sections
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  showNavbar?: boolean | null;
  showFooter?: boolean | null;
  /**
   * Small label above the title (e.g. 'AI Technology for Your Career')
   */
  heroBadge?: string | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroCtaText?: string | null;
  heroCtaLink?: string | null;
  /**
   * Optional image to replace the default job card illustration
   */
  heroImage?: (string | null) | Media;
  whatIsTitle?: string | null;
  whatIsDescription?: string | null;
  whatIsCards?:
    | {
        badge?: string | null;
        title?: string | null;
        description?: string | null;
        ctaText?: string | null;
        ctaLink?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  mechanismTitle?: string | null;
  mechanismDescription?: string | null;
  mechanismSteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  mechanismCtaText?: string | null;
  mechanismCtaLink?: string | null;
  frameworkBadge?: string | null;
  frameworkTitle?: string | null;
  frameworkTitleLine2?: string | null;
  frameworkDescription?: string | null;
  frameworkDimensions?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  employeesBadge?: string | null;
  employeesTitle?: string | null;
  /**
   * The accented part of the title (shown in primary color)
   */
  employeesTitleHighlight?: string | null;
  employeesSubtitle?: string | null;
  employeesBenefits?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  employeesCtaText?: string | null;
  employeesCtaLink?: string | null;
  employeesImage?: (string | null) | Media;
  employersBadge?: string | null;
  employersTitle?: string | null;
  /**
   * The accented part of the title (shown in primary color)
   */
  employersTitleHighlight?: string | null;
  employersSubtitle?: string | null;
  employersBenefits?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  employersCtaText?: string | null;
  employersCtaLink?: string | null;
  employersImage?: (string | null) | Media;
  pricingTitle?: string | null;
  pricingSubtitle?: string | null;
  faqTitle?: string | null;
  faqSubtitle?: string | null;
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  faqContactEmail?: string | null;
  blogTitle?: string | null;
  blogSubtitle?: string | null;
  blogCtaText?: string | null;
  finalCtaTitle?: string | null;
  finalCtaDescription?: string | null;
  finalCtaButtonText?: string | null;
  finalCtaButtonLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit the blog listing page header and settings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: string;
  /**
   * Main heading on the blog listing page
   */
  title?: string | null;
  /**
   * Description text below the title
   */
  subtitle?: string | null;
  /**
   * Number of blog posts to show per page
   */
  postsPerPage?: number | null;
  showNavbar?: boolean | null;
  showFooter?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit navigation links and CTA button
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: string;
  /**
   * Displayed as the logo text in the navbar
   */
  appName?: string | null;
  navLinks?:
    | {
        label: string;
        /**
         * e.g. /#features, /blog, /pricing
         */
        url: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Text shown on the main CTA button when user is not logged in
   */
  ctaText?: string | null;
  ctaLink?: string | null;
  /**
   * Text shown when user is logged in
   */
  dashboardText?: string | null;
  dashboardLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit footer links, social media, and contact info
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Footer description text below the logo
   */
  description?: string | null;
  copyright?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: "facebook" | "twitter" | "instagram" | "linkedin" | "youtube" | "github";
        url: string;
        id?: string | null;
      }[]
    | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logo_select".
 */
export interface LogoSelect<T extends boolean = true> {
  light?: T;
  dark?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  plans?:
    | T
    | {
        key?: T;
        name?: T;
        description?: T;
        price?: T;
        cta?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        productKey?: T;
        isActive?: T;
        sortOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  showNavbar?: T;
  showFooter?: T;
  heroBadge?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroCtaText?: T;
  heroCtaLink?: T;
  heroImage?: T;
  whatIsTitle?: T;
  whatIsDescription?: T;
  whatIsCards?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        ctaText?: T;
        ctaLink?: T;
        image?: T;
        id?: T;
      };
  mechanismTitle?: T;
  mechanismDescription?: T;
  mechanismSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  mechanismCtaText?: T;
  mechanismCtaLink?: T;
  frameworkBadge?: T;
  frameworkTitle?: T;
  frameworkTitleLine2?: T;
  frameworkDescription?: T;
  frameworkDimensions?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  employeesBadge?: T;
  employeesTitle?: T;
  employeesTitleHighlight?: T;
  employeesSubtitle?: T;
  employeesBenefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  employeesCtaText?: T;
  employeesCtaLink?: T;
  employeesImage?: T;
  employersBadge?: T;
  employersTitle?: T;
  employersTitleHighlight?: T;
  employersSubtitle?: T;
  employersBenefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  employersCtaText?: T;
  employersCtaLink?: T;
  employersImage?: T;
  pricingTitle?: T;
  pricingSubtitle?: T;
  faqTitle?: T;
  faqSubtitle?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  faqContactEmail?: T;
  blogTitle?: T;
  blogSubtitle?: T;
  blogCtaText?: T;
  finalCtaTitle?: T;
  finalCtaDescription?: T;
  finalCtaButtonText?: T;
  finalCtaButtonLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  postsPerPage?: T;
  showNavbar?: T;
  showFooter?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  appName?: T;
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  ctaText?: T;
  ctaLink?: T;
  dashboardText?: T;
  dashboardLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  copyright?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
