import type { CollectionConfig } from "payload";

export const JWKS: CollectionConfig = {
  slug: "jwks",
  admin: {
    hidden: true,
  },
  fields: [
    /* id, createdAt, and updatedAt are autogenerated by Payload */
    {
      name: "publicKey",
      type: "textarea",
      required: true,
      admin: {
        description: "The public part of the web key",
      },
    },
    {
      name: "privateKey",
      type: "textarea",
      required: true,
      admin: {
        description: "The private part of the web key",
      },
    },
    {
      name: "expiresAt",
      type: "date",
      required: false,
      index: true,
      admin: {
        description: "Timestamp of when the web key expires",
        date: {
          pickerAppearance: "dayAndTime",
        },
      },
    },
  ],
};
