import type { CollectionConfig, CollectionSlug } from "payload";

import { OAuthApplication } from "./OAuthApplication";

export const OAuthConsent: CollectionConfig = {
  slug: "oauth_consent",
  admin: {
    hidden: true,
  },
  fields: [
    /* id, createdAt, and updatedAt is autogenerated by Payload */
    {
      name: "userId",
      type: "relationship",
      relationTo: "users",
      required: true,
      index: true,
      admin: {
        description: "ID of the user who gave consent",
      },
    },
    {
      name: "clientId",
      type: "relationship",
      relationTo: OAuthApplication.slug as CollectionSlug,
      required: true,
      index: true,
      admin: {
        description: "ID of the OAuth client",
      },
    },
    {
      name: "scopes",
      type: "text",
      required: false,
      admin: {
        description: "Comma-separated list of scopes consented to",
      },
    },
    {
      name: "consentGiven",
      type: "checkbox",
      defaultValue: true,
      required: true,
      admin: {
        description: "Indicates if consent was given",
      },
    },
  ],
};
