import type { CollectionConfig, CollectionSlug } from "payload";

import { OAuthApplication } from "./OAuthApplication";

export const OAuthAccessToken: CollectionConfig = {
  slug: "oauth_access_token",
  admin: {
    hidden: true,
  },
  fields: [
    /* id, createdAt, and updatedAt is autogenerated by Payload */
    {
      name: "accessToken",
      type: "text",
      required: true,
      unique: true,
      index: true,
      admin: {
        description: "Access token issued to the client",
      },
    },
    {
      name: "refreshToken",
      type: "text",
      required: false,
      unique: true,
      index: true,
      admin: {
        description: "Refresh token issued to the client",
      },
    },
    {
      name: "accessTokenExpiresAt",
      type: "date",
      required: true,
      admin: {
        description: "Expiration date of the access token",
        date: {
          pickerAppearance: "dayAndTime",
        },
      },
    },
    {
      name: "refreshTokenExpiresAt",
      type: "date",
      required: false,
      admin: {
        description: "Expiration date of the refresh token",
        date: {
          pickerAppearance: "dayAndTime",
        },
      },
    },
    {
      name: "clientId",
      type: "relationship",
      relationTo: OAuthApplication.slug as CollectionSlug,
      required: true,
      index: true,
    },
    {
      name: "userId",
      type: "relationship",
      relationTo: "users",
      required: true,
      index: true,
      admin: {
        description: "ID of the user associated with the token",
      },
    },
    {
      name: "scopes",
      type: "text",
      required: false,
      admin: {
        description: "Comma-separated list of scopes granted",
      },
    },
  ],
};
