import type { CollectionConfig } from "payload";

export const OAuthApplication: CollectionConfig = {
  slug: "oauth_application",
  admin: {
    hidden: true,
  },
  fields: [
    /* id, createdAt, and updatedAt is autogenerated by Payload */
    {
      name: "clientId",
      type: "text",
      required: true,
      unique: true,
      index: true,
      admin: {
        description: "Unique identifier for each OAuth client",
      },
    },
    {
      name: "clientSecret",
      type: "text",
      required: false,
      admin: {
        description: "Secret key for the OAuth client. Optional for public clients using PKCE.",
      },
    },
    {
      name: "name",
      type: "text",
      required: true,
      admin: {
        description: "Name of the OAuth client",
      },
    },
    {
      name: "redirectURLs",
      type: "text",
      required: false,
      admin: {
        description: "Comma-separated list of redirect URLs",
      },
    },
    {
      name: "metadata",
      type: "textarea",
      required: false,
      admin: {
        description: "Additional metadata for the OAuth client (JSON string)",
      },
    },
    {
      name: "type",
      type: "select",
      required: true,
      options: [
        { label: "Web", value: "web" },
        { label: "Mobile", value: "mobile" },
        { label: "Public", value: "public" },
      ],
      defaultValue: "web",
      admin: {
        description: "Type of OAuth client",
      },
    },
    {
      name: "disabled",
      type: "checkbox",
      defaultValue: false,
      admin: {
        description: "Indicates if the client is disabled",
      },
    },
    {
      name: "userId",
      type: "relationship",
      relationTo: "users",
      required: false,
      index: true,
      admin: {
        description: "ID of the user who owns the client (optional)",
      },
    },
  ],
};
