import { auth } from "@/server/auth/auth";
import type { CollectionConfig } from "payload";

export const Users: CollectionConfig = {
  slug: "users",
  labels: {
    singular: { lt: "Naudotojas", en: "User" },
    plural: { lt: "Naudotojai", en: "Users" },
  },
  admin: {
    useAsTitle: "email",
    group: { lt: "Naudotojai", en: "Users" },
  },
  auth: {
    disableLocalStrategy: true, // We should disable this since we use Better Auth now
    strategies: [
      {
        name: "better-auth",
        authenticate: async ({ headers, payload }) => {
          try {
            const userSession = await auth.api.getSession({ headers });

            if (!userSession || !userSession.user) return { user: null };

            const userData = await payload.findByID({
              collection: "users",
              id: userSession?.user?.id,
            });

            return {
              user: {
                ...userData,
                collection: "users",
              },
            };
          } catch (err) {
            payload.logger.error(err);
            return { user: null };
          }
        },
      },
    ],
  },
  endpoints: [
    {
      path: "/logout",
      method: "post",
      handler: async req => {
        await auth.api.signOut({
          headers: req.headers,
        });
        return Response.json(
          {
            message: "Token revoked successfully",
          },
          {
            status: 200,
            headers: req.headers,
          }
        );
      },
    },
  ],
  access: {
    admin: async ({ req }) => {
      // Check if user is authenticated
      if (!req.user?.id) {
        return false;
      }

      // Check if user has admin role
      return req.user.role === "admin";
    },
  },
  fields: [
    /*  id, createdAt, and updatedAt is autogenerated by Payload */
    /* Add more fields as you need */
    {
      name: "name",
      label: { lt: "Vardas", en: "Name" },
      type: "text",
      required: true,
      index: true,
    },
    {
      name: "email",
      label: { lt: "El. paštas", en: "Email" },
      type: "text",
      required: true,
      unique: true,
      index: true,
    },
    {
      name: "role",
      label: { lt: "Rolė", en: "Role" },
      type: "select",
      required: true,
      defaultValue: "user",
      options: [
        {
          label: { lt: "Naudotojas", en: "User" },
          value: "user",
        },
        {
          label: { lt: "Administratorius", en: "Admin" },
          value: "admin",
        },
      ],
      admin: {
        position: "sidebar",
      },
    },
    {
      name: "banned",
      label: { lt: "Užblokuotas", en: "Banned" },
      type: "checkbox",
      defaultValue: false,
      admin: {
        position: "sidebar",
        description: "Whether the user is banned",
      },
    },
    {
      name: "banReason",
      label: { lt: "Blokavimo priežastis", en: "Ban Reason" },
      type: "text",
      admin: {
        position: "sidebar",
        description: "Reason for the ban",
        condition: data => data.banned === true,
      },
    },
    {
      name: "banExpires",
      label: { lt: "Blokavimo pabaiga", en: "Ban Expires" },
      type: "date",
      admin: {
        position: "sidebar",
        description: "When the ban expires (leave empty for permanent ban)",
        date: {
          pickerAppearance: "dayAndTime",
        },
        condition: data => data.banned === true,
      },
    },
    {
      name: "emailVerified",
      label: { lt: "El. paštas patvirtintas", en: "Email Verified" },
      type: "checkbox",
      required: true,
    },
    {
      name: "image",
      label: { lt: "Nuotrauka", en: "Image" },
      type: "text",
    },
  ],
};
